action_space:
  n_eval_episodes: 1000
  n_eval_envs: 1
  render_mode: human
  device: cpu
  discrete_action_space: false
  model_vs_model: false
  weak_opponent: true
  start_method: "spawn"
  models:
    [
      "../final_exp_2/td3_0_no_self",
      "../final_exp_2/td3_0_no_self",
      "../final_exp_2/td3_0_with_self",
      "../final_exp_2/td3_0_with_self",
      "../final_exp_2/td3_2_with_self",
      "../final_exp_2/td3_2_with_self",
      "../final_exp_2/td3_2_no_self",
      "../final_exp_2/td3_2_no_self",
    ]
  opponents:
    ["weak", "strong", "weak", "strong", "weak", "strong", "weak", "strong"]
  save_location: "../actionspace_td3"
  render: false
