test:
  model_1_dir: "../final_exp_2/td3_2_with_self"
  model_2_dir: "../best_agents/trial_8"
  n_eval_episodes: 100
  n_eval_envs: 1
  model_vs_model: false
  render_mode: human
  device: cpu
  discrete_action_space: false
  dict_observation_space: false
  weak_opponent: false
  start_method: "spawn"
