logs:
  csv_filename: "trainer_test.csv"
  tensorboard_log_dir: "../trainer_test"
  run_name: "trainer_test"

hyperparameter:
  do_hyperparameter_search: false
  study_name: "td3"
  storage: "sqlite:///td3.db"
  n_trials: 200
  n_jobs: 1
  n_startup_trials: 5
  csv_filename: "hyperparameter_search.csv"

training:
  n_train_envs: 128
  n_eval_envs: 10
  n_evaluations: 40
  n_timesteps: 40000000
  normalize: true
  steps_for_threshold: 5000100
  reward_threshold: 5
  steps_for_threshold_2: 3000100
  reward_threshold_2: 0
  start_method: "spawn"

agent:
  agent: "TD3"
  policy: "TD3_MultiInputPolicy"
  normalize: true
  negative_reward: true
  discrete_action_space: false
  dict_observation_space: true

agent_parameter: # ignored if hyperparameter search is enabled
  buffer_size: 1000000
  batch_size: 2048
  gamma: 0.99
  learning_rate: 0.0009200000000000001
  device: cpu
  train_freq: 512
  gradient_steps: 512
  policy_kwargs: { net_arch: [256, 256] }
  tau: 0.02
  policy_delay: 1
  target_noise_clip: 0.1

selfplay:
  selfplay: false
  add_opponent_every_n_steps: 1000000
  change_opponent_every_n_steps: 128000
  first_opponent_after_n_steps: 1000000
  how_many_to_add: 1
  best_agents_path:
  add_to_best_agents_when_mean_reward_is_above: 9.6
  add_to_best_agents_when_best_agents_mean_reward_is_above: 1
